### ISSUE TITLE
Add more themes

### ISSUE THREAD

**Issue by bielej** [sbs20/filenotes-android#3]
Adding more themes (like AMOLED black) and ability to change accent color would be appreciated.

**Comment by sbs20** [comment]
Will take a look and see what I can do. Any particular accent colours you'd like? I suspect I might not get around to the changeable accents that quickly!

**Comment by bielej** [comment]
Something AMOLED friendly :)
Black backgroud + #3498db as accent color maybe?

**Comment by sbs20** [comment]
Update on its way!

**Comment by bielej** [comment]
Looks awesome :D
